language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
   - DRF="djangorestframework==3.4.6"
  matrix:
   - DJANGO="django==1.8.14"
   - DJANGO="django==1.9.9"
   - DJANGO="django==1.10.1"
   - DJANGO="django==1.10.1" LINT=1
before_script:
 - createdb -Upostgres wqdb_test
 - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
install:
 - pip install $DJANGO
 - pip install $DRF
 - pip install flake8
script:
 - ./runtests.sh
